apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip # Specifies that the target type is IP
spec:
  ingressClassName: "alb" 
  rules:
    - http:
        paths:
        ### BACKEND ###
          - backend:
              service:
                name: my-service
                port:
                  number: 8000
            path: /admin
            pathType: Prefix
          - backend:
              service:
                name: my-service
                port:
                  number: 8000
            path: /user
            pathType: Prefix
          - backend:
              service:
                name: my-service
                port:
                  number: 8000
            path: /job
            pathType: Prefix
          - backend:
              service:
                name: my-service
                port:
                  number: 8000
            path: /application
            pathType: Prefix
          - backend:
              service:
                name: my-service
                port:
                  number: 8000
            path: /api
            pathType: Prefix
          - backend:
              service:
                name: my-service
                port:
                  number: 8000
            path: /media
            pathType: Prefix
          - backend:
              service:
                name: my-service
                port:
                  number: 8000
            path: /static
            pathType: Prefix
          ### FRONTEND ###
          - backend:
              service:
                name: my-service
                port:
                  number: 3000
            path: /static/js/bundle.js
            pathType: Prefix
          - backend:
              service:
                name: my-service
                port:
                  number: 3000
            path: /fonts
            pathType: Prefix
          - backend:
              service:
                name: my-service
                port:
                  number: 3000
            path: /
            pathType: Prefix
          ### websoocket Connection
          - backend:
              service:
                name: my-service
                port:
                  number: 8002
            path: /ws  # Assuming WebSocket connections use this path
            pathType: Prefix

