apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resume-volume-pvc  # Name of the PVC
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi  # Size of the storage

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: referral
        image: jerryji040506/referral:linux
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 3000
        - containerPort: 8001
        env:
        - name: DB_HOST
          value: "pg-service"  # match pg-service name
        - name: REDIS_HOST
          value: "redis-service"  # match redis-service name
        - name: RABBIT_HOST
          value: "rabbit-service"  # match rabbit-service name
        volumeMounts:
        - name: resume-volume
          mountPath: /app/backend/media # match resume-volume
      volumes:
        - name: resume-volume
          persistentVolumeClaim:
            claimName: resume-volume-pvc  # Use the PVC name here
---
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - name: react
      port: 3000
      targetPort: 3000
    - name: django
      port: 8000
      targetPort: 8000
    - name: fastapi
      port: 8002
      targetPort: 8001