apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  annotations:
    meta.helm.sh/release-name:  {{ .Release.Name }}
    meta.helm.sh/release-namespace: default
data:
  POSTGRES_DB: referral_system
  POSTGRES_USER: referral_user
  POSTGRES_PASSWORD: jerry