apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Release.Name}}-postgres-statefulset
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: gp2
---
apiVersion: v1
kind: Service # ADD IP HASH configuration
metadata:
  name: {{.Release.Name}}-pg-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432 # PostgreSQL default port
