apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resume-volume-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi