apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Release.Name}}-redis-statefulset
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates: 
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: gp2  
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379