apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resume-volume-pvc
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi  # Size of the storage

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCouxnt }}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: referral
        image: jerryji040506/referral:linux
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 3000
        - containerPort: 8001
        env:
        - name: DB_HOST
          value: {{.Release.Name}}-pg-service # match pg-service name
        - name: REDIS_HOST
          value: {{.Release.Name}}-redis-service  # match redis-service name
        - name: RABBIT_HOST
          value: {{.Release.Name}}-rabbit-service  # match rabbit-service name
        volumeMounts:
        - name: resume-volume
          mountPath: /app/backend/media # match resume-volume
      volumes:
        - name: resume-volume
          persistentVolumeClaim:
            claimName: resume-volume-pvc  # Use the PVC name here
---
kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-my-service
spec:
  selector:
    app: my-app
  ports:
    - name: react
      port: 3000
      targetPort: 3000
    - name: django
      port: 8000
      targetPort: 8000
    - name: fastapi
      port: 8002
      targetPort: 8001