### PG SERVICE
apiVersion: v1
kind: Service # ADD IP HASH configuration
metadata:
  name: pg-{{.Release.Name}}
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432 # PostgreSQL default port

---
### REDIS SERVICE
apiVersion: v1
kind: Service
metadata:
  name: redis-{{.Release.Name}}
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379

---
### RABBITMQ SERVICE
apiVersion: v1
kind: Service
metadata:
  name: rabbit-{{.Release.Name}}
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      name: port1
      port: 5672  
    - protocol: TCP
      name: port2
      port: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: referral-{{.Release.Name}}
spec:
  selector:
    app: my-app
  ports:
    - name: react
      port: 3000
      targetPort: 3000
    - name: django
      port: 8000
      targetPort: 8000
    - name: fastapi
      port: 8001
      targetPort: 8001